# Generated by Django 4.2.1 on 2023-05-04 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=512, verbose_name="App name")),
                ("token", models.CharField(max_length=512, verbose_name="token")),
                ("url", models.CharField(max_length=512, verbose_name="Url")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "launch_status",
                    models.BooleanField(default=0, verbose_name="Status"),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Login id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_name", models.CharField(max_length=255)),
                ("link_status", models.BooleanField(default=0)),
                ("media_status", models.BooleanField(default=0)),
                (
                    "bot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.bot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question_command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "command_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.command",
                        verbose_name="cmdId",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.TextField(verbose_name="media")),
                (
                    "command_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.command",
                        verbose_name="cmdId",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mail_command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.TextField(verbose_name="mail")),
                ("date", models.DateField(default=datetime.datetime.now)),
                (
                    "command_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.command",
                        verbose_name="cmdId",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link_command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkcommands_current",
                        to="api.command",
                        verbose_name="curCmd",
                    ),
                ),
                (
                    "following_command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkcommands_following",
                        to="api.command",
                        verbose_name="flwCmd",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="command",
            name="type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.type_command"
            ),
        ),
        migrations.CreateModel(
            name="Bot_chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField()),
                (
                    "bot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.bot"
                    ),
                ),
            ],
        ),
    ]
