# Generated by Django 4.2 on 2023-04-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bot'),
    ]

    def create_data(apps, schema_editor):
        Bot = apps.get_model('accounts', 'Bot')
        Bot(name="Joe Silver",
                photo='media/photo/nophoto.png').save()
        Bot(name="John Smith",
                photo='media/photo/nophoto.png').save()
        Bot(name="Alex Smth",
                photo='media/photo/nophoto.png').save()
        Bot(name="Kira Night",
                photo='media/photo/nophoto.png').save()
        Bot(name="Amanda Lex",
                photo='media/photo/nophoto.png').save()
        Bot(name="Oni Musha",
                photo='media/photo/nophoto.png').save()

    operations = [
        migrations.RunPython(create_data),
    ]


